/*You are given a string s
 of length n
. Let's define two operations you can apply on the string:

remove the first character of the string;
remove the second character of the string.
Your task is to find the number of distinct non-empty strings that can be generated by applying the given operations on the initial string any number of times (possibly zero), in any order.

Input
Each test consists of multiple test cases. The first line contains a single integer t
 (1≤t≤104
) — the number of test cases. The description of the test cases follows.

The first line of each test case contains n
 (1≤n≤105
) — the length of the string.

The second line of each test case contains the string s
. It is guaranteed that the string only contains lowercase letters of the English alphabet.

It is guaranteed that the sum of n
 over all test cases does not exceed 2⋅105
.

Output
For each test case, output a single integer: the number of distinct non-empty strings you can get.
*/
#include <bits/stdc++.h>
using namespace std;
#define ll long long
#define mod 1000000007
void solve()
{
    int n;
    cin >> n;
    string s;
    cin >> s;
    map<char, int> map;
    ll ans=(ll)n;

    for(int i=0;i<n-1;i++){
        if(map[s[i]]){
            continue;
        }
        map[s[i]] = 1;
        for(int j=i+1;j<n;j++){
            if(s[i]!=s[j]){
                ans++;
            }
        }
    }
    cout << ans << endl;
}
int main() {
    ios_base::sync_with_stdio(false);cin.tie(NULL);cout.tie(NULL);
#ifndef ONLINE_JUDGE
    freopen("input.txt", "r", stdin);
    freopen("output.txt", "w", stdout);
#endif

    ll test=1;
cin>>test;
    while(test--)
    {
        solve();
    }
    return 0;
}